name: Set up row
description: Install row.

inputs:
  version:
    description: 'row version to install.'
    required: false
    default: '0.7.1'
  platform:
    description: 'Download executables for the given platform.'
    required: false
    default: x86_64-unknown-linux-musl

runs:
  using: "composite"
  steps:
  - name: Install row
    run: |
      mkdir -p "$HOME/.cargo/bin"
      curl -sSL "https://github.com/glotzerlab/row/releases/download/${{ inputs.version }}/row-${{ inputs.version }}-${{ inputs.platform }}.tar.zst" | tar --zstd -xv --directory "$HOME/.cargo/bin"
    shell: bash
