name: Set up uv
description: Install uv and synchronize the environment with a given lock file.

inputs:
  version:
    description: 'uv version to install.'
    required: false
    default: '0.11.18'
  lockfile:
    description: 'Packages to install.'
    required: false
    default: ''
  only-binary:
    description: 'Value to pass to the --only-binary option.'
    required: false
    default: ':all:'

runs:
  using: "composite"
  steps:
  - name: Setup uv
    uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
    with:
      version: ${{ inputs.version }}

  - name: Install packages
    if: ${{ inputs.lockfile != '' }}
    run: "uv pip sync ${{ inputs.lockfile }} --only-binary=${{ inputs.only-binary }} --system --reinstall"
    shell: bash
