name: Set up uv
description: Install uv and synchronize the environment with a given lock file.

inputs:
  version:
    description: 'uv version to install.'
    required: false
    default: '0.2.6'
  lockfile:
    description: 'Packages to install.'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
  - name: Install uv
    run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/${{ inputs.version }}/uv-installer.sh | bash
    shell: bash

  - name: Install
    if: ${{ inputs.lockfile != '' }}
    run: "uv pip sync ${{ inputs.lockfile }} --only-binary :all: --system --reinstall"
    shell: bash
