name: Run prek
description: Install and run prek.

inputs:
  version:
    description: 'prek version to install.'
    required: false
    default: '0.2.1'
  path:
    description: 'Execute prek in this path.'
    required: false
    default: ''
  platform:
    description: 'Download executables for the given platform.'
    required: false
    default: x86_64-unknown-linux-musl

runs:
  using: "composite"
  steps:
  - name: Install prek
    run: |
      : Install prek
      mkdir -p "$HOME/.cargo/bin"
      curl -sSL "https://github.com/j178/prek/releases/download/v${{ inputs.version }}/prek-${{ inputs.platform }}.tar.gz" | tar -xz --strip-components=1 --directory "$HOME/.cargo/bin"
      echo "PREK_COLOR=always" >> "$GITHUB_ENV"
    shell: bash
  - run: prek run --all-files --show-diff-on-failure --verbose
    working-directory: ${{ inputs.path }}
    shell: bash
