name: Test

on:
  pull_request:
      types: [opened, labeled, reopened, synchronize]

  workflow_dispatch:

  push:
    branches:
    - trunk

jobs:
  setup_uv_default:
    name: setup-uv [default]
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: "3.13"
    - name: Set up Python environment
      uses: ./setup-uv
    - run: uv --version

  setup_uv_version:
    name: setup-uv [version]
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: "3.13"
    - name: Set up Python environment
      uses: ./setup-uv
      with:
        version: 0.4.0
    - run: uv --version

  setup_uv_lockfile:
    name: setup-uv [only-binary=:all:]
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: "3.13"
    - name: Set up Python environment
      uses: ./setup-uv
      with:
        lockfile: .github/workflows/lockfile.txt
    - run: uv --version
    - run: python -m build --version

  setup_uv_lockfile_only_binary_none:
    name: setup-uv [only-binary=:none:]
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: "3.13"
    - name: Set up Python environment
      uses: ./setup-uv
      with:
        lockfile: .github/workflows/lockfile.txt
        only-binary: ":none:"
    - run: uv --version
    - run: python -m build --version

  setup_mdbook:
    name: setup-mdbook [default]
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up mdbook
      uses: ./setup-mdbook
    - run: mdbook --version

  setup_cargo_bundle_licenses:
    name: setup-cargo-bundle-licenses [default]
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up cargo-bundle-licenses
      uses: ./setup-cargo-bundle-licenses
    - run: cargo bundle-licenses --version

  setup_row:
    name: setup-row [default]
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up row
      uses: ./setup-row
    - run: row --version
    - run: row --help

  tests_complete:
    name: All tests
    if: always()
    needs:
    - setup_uv_default
    - setup_uv_version
    - setup_uv_lockfile
    - setup_uv_lockfile_only_binary_none
    - setup_mdbook
    - setup_cargo_bundle_licenses
    - setup_row
    runs-on: ubuntu-24.04

    steps:
    - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Done
      run: exit 0
