name: Test

on:
  pull_request:

  workflow_dispatch:

  push:
    branches:
    - trunk

jobs:
  setup_uv_defaults:
    name: setup-uv [default]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.12"
    - name: Set up Python environment
      uses: ./setup-uv
    - run: uv --version

  setup_uv_version:
    name: setup-uv [version]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.12"
    - name: Set up Python environment
      uses: ./setup-uv
      with:
        version: 0.2.2
    - run: uv --version

  setup_uv_lockfile:
    name: setup-uv [lockfile]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.12"
    - name: Set up Python environment
      uses: ./setup-uv
      with:
        lockfile: .github/workflows/lockfile.txt
    - run: uv --version
    - run: python -m build --version

