name: Test

on:
  pull_request:

  workflow_dispatch:

  push:
    branches:
    - trunk

jobs:
  setup_uv_default:
    name: setup-uv [default]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Set up Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.12"
    - name: Set up Python environment
      uses: ./setup-uv
    - run: uv --version

  setup_uv_version:
    name: setup-uv [version]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Set up Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.12"
    - name: Set up Python environment
      uses: ./setup-uv
      with:
        version: 0.2.2
    - run: uv --version

  setup_uv_lockfile:
    name: setup-uv [lockfile]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Set up Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.12"
    - name: Set up Python environment
      uses: ./setup-uv
      with:
        lockfile: .github/workflows/lockfile.txt
    - run: uv --version
    - run: python -m build --version

  setup_mdbook:
    name: setup-mdbook [default]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Set up mdbook
      uses: ./setup-mdbook
    - run: mdbook --version
    - run: mdbook-linkcheck --version

  setup_cargo_bundle_licenses:
    name: setup-cargo-bundle-licenses [default]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Set up cargo-bundle-licenses
      uses: ./setup-cargo-bundle-licenses
    - run: cargo bundle-licenses --version

  update_conda_lockfiles:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref != 'update-conda-lockfiles' }}
    uses: ./.github/workflows/update-conda-lockfiles.yaml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
      path: test/update-conda-lockfile

  tests_complete:
    name: All tests
    if: always()
    needs:
    - setup_uv_default
    - setup_uv_version
    - setup_uv_lockfile
    - setup_mdbook
    - setup_cargo_bundle_licenses
    - update_conda_lockfiles
    runs-on: ubuntu-latest

    steps:
    - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Done
      run: exit 0
