name: Update uv lockfiles

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      command:
        default: ./update-lockfiles.sh
        required: false
        type: string
      path:
        default: .github/workflows/environments
        required: false
        type: string

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        path: code
        ref: ${{ inputs.branch }}

    - uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
      id: generate-token
      with:
        app-id: ${{ secrets.PR_SUBMITTER_APP_ID }}
        private-key: ${{ secrets.PR_SUBMITTER_PRIVATE_KEY }}

    - name: Create python environment
      uses: mamba-org/setup-micromamba@617811f69075e3fd3ae68ca64220ad065877f246 # v2.0.0
      with:
        micromamba-version: '2.0.2-2'
        environment-name: update
        create-args: >-
          python=3.12
          uv
        micromamba-root-path: ${{ github.workspace }}/micromamba

    - name: Configure conda environment variables
      run: |
        echo "$MAMBA_ROOT_PREFIX/envs/update/bin" >> $GITHUB_PATH

    - name: Update lockfiles
      run: ${{ inputs.command }}
      working-directory: code/${{ inputs.path }}

    - name: Create pull request
      uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
      with:
        base: ${{ inputs.branch }}
        path: code
        commit-message: "Update uv lockfiles"
        branch: update-uv-lockfiles
        delete-branch: true
        title: Update uv lockfiles on ${{ inputs.branch }}
        body: Automated changes by `${{ inputs.command }}`.
        token: ${{ steps.generate-token.outputs.token }}
