name: Update conda lockfiles

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      command:
        default: ./update-lockfiles.sh
        required: false
        type: string
      path:
        default: .github/workflows/environments
        required: false
        type: string

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        path: code
        ref: ${{ inputs.branch }}

    - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
      id: generate-token
      with:
        app-id: ${{ secrets.PR_SUBMITTER_APP_ID }}
        private-key: ${{ secrets.PR_SUBMITTER_PRIVATE_KEY }}

    - name: Create python environment
      uses: mamba-org/setup-micromamba@b09ef9b599704322748535812ca03efb2625677b # v2.0.5
      with:
        micromamba-version: '2.0.2-2'
        environment-name: update
        create-args: >-
          python=3.12
          conda-lock
        micromamba-root-path: ${{ github.workspace }}/micromamba

    - name: Configure conda environment variables
      run: |
        echo "$MAMBA_ROOT_PREFIX/envs/update/bin" >> $GITHUB_PATH

    - name: Update lockfiles
      run: ${{ inputs.command }}
      working-directory: code/${{ inputs.path }}

    - name: Create pull request
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        base: ${{ inputs.branch }}
        path: code
        commit-message: "Update conda lockfiles"
        branch: update-conda-lockfiles
        delete-branch: true
        title: Update conda lockfiles on ${{ inputs.branch }}
        body: Automated changes by `${{ inputs.command }}`.
        token: ${{ steps.generate-token.outputs.token }}
